#!/bin/bash
BASE=$(cd `dirname $0`; pwd)
LD_LIBRARY_PATH=$BASE/lib:$LD_LIBRARY_PATH && $BASE/nginx -p $BASE 

user root;
worker_processes auto;
error_log ./logs/error.log;
pid ./nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  ./logs/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             ./mime.types;
    default_type        application/octet-stream;
	
    server {
        listen       880 default_server;
        listen       8443 ssl;
        server_name  test.com;
        root         ./html;

        ssl_certificate ./test.crt;
        ssl_certificate_key ./test.key;

        location / {
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
}


