#!/bin/bash

LINUX=linux-3.10.105
BUSYBOX=busybox-1.26.2

# setting up linux source tree
if [ ! -d $LINUX ]
then
	yum -y install gcc ncurses ncurses-devel bc telnet wget glibc-static lbzip2
	wget https://mirrors.aliyun.com/linux-kernel/v3.x/$LINUX.tar.xz
	tar xf $LINUX.tar.xz
fi

/bin/cp -f ./kernel_config $LINUX/.config
yes "" | make -C $LINUX oldconfig

# setting up busybox source tree
if [ ! -d $BUSYBOX ]
then
	wget http://busybox.net/downloads/$BUSYBOX.tar.bz2
	tar xf $BUSYBOX.tar.bz2
fi

make -C $BUSYBOX defconfig
${LINUX}/scripts/config --file ${BUSYBOX}/.config --enable CONFIG_STATIC
${LINUX}/scripts/config --file ${BUSYBOX}/.config --enable CONFIG_INSTALL_NO_USR
${LINUX}/scripts/config --file ${BUSYBOX}/.config --disable CONFIG_INETD
${LINUX}/scripts/config --file ${BUSYBOX}/.config --disable CONFIG_FEATURE_MOUNT_NFS

yes "" | make -C $BUSYBOX oldconfig
