# NOTE:
# When build executable with this Makefile, you'll see lots of warnings like:
# ld: comiler-specific.o: warning: linking PIC files with non-PIC files
#
# This will not harm your targets, and do NOT try to resolve this issue.
#
# As Ralf Baechle <ralf@linux-mips.org> says:
#
# > What is the correct way of cross-compiling a non-pic static glibc?
#
# Forget it.  The non-PIC support for glibc is rotting away since ages.
#
# Why do you want a non-PIC glibc?
#
#  Ralf

#ifeq ($(ARCH),mips)
	CROSS_COMPILE = mips-linux-gnu-
	CFLAGS := -mabi=32 -mno-abicalls -EL -O2 -g -Wall -Wno-unused-parameter
	LDFLAGS = -static -EL
#endif

CC = $(CROSS_COMPILE)gcc
LD = $(CROSS_COMPILE)gcc

TARGETS := and array foo ascii char memtest sizeofarray ifdef \
	sizeof typeof shift popcount string2hex zero_array \
	asprintf microsoft bit_complete gcc_optimise	   \
	comiler-specific max malloc0 endian odd_array asm

OBJS = $(TARGETS:%=%.o)

all : $(TARGETS)

$(TARGETS): $(TARGETS:%=%.o)
	$(LD) -o $@ $(LDFLAGS) $(@:%=%.o)

clean:
	rm -f $(OBJS)
	rm -f $(TARGETS)
